catalogo.add(crearCancion("Me volvieron a hablar del amor", "Andrés Calamaro", "Rock", 2004));
catalogo.add(crearCancion("Oye mi amor", "Maná", "Rock/Pop", 1992));
catalogo.add(crearCancion("De música ligera", "Soda Stereo", "Rock", 1990));
catalogo.add(crearCancion("Tren al sur", "Los Prisioneros", "Rock", 1990));
catalogo.add(crearCancion("Lamento boliviano", "Los Enanitos Verdes", "Rock", 1994));
catalogo.add(crearCancion("Persiana americana", "Soda Stereo", "Rock", 1986));
catalogo.add(crearCancion("Aquel lugar", "El Bordo", "Rock", 2012));
catalogo.add(crearCancion("Mariposa tecknicolor", "Fito Páez", "Rock/Pop", 1994));
catalogo.add(crearCancion("Gitana", "Willie Colón", "Salsa", 1977));
catalogo.add(crearCancion("Deseándote", "Frankie Ruiz", "Salsa", 1986));
catalogo.add(crearCancion("Lluvia", "Eddie Santiago", "Salsa", 1988));
catalogo.add(crearCancion("Te conozco bien", "Marc Anthony", "Salsa", 1995));
catalogo.add(crearCancion("El gran varón", "Willie Colón", "Salsa", 1989));
catalogo.add(crearCancion("Si te vas", "Shakira", "Pop/Rock", 1998));
catalogo.add(crearCancion("A dónde van los corazones", "Marciano Cantero", "Rock", 1986));
catalogo.add(crearCancion("El farolito", "Los Fabulosos Cadillacs", "Rock/Ska", 1997));
catalogo.add(crearCancion("Pétalo de sal", "Fito Páez", "Rock/Pop", 1999));
catalogo.add(crearCancion("Muévelo", "Los Auténticos Decadentes", "Rock/Fusión", 1995));
catalogo.add(crearCancion("Me arde", "La Ley", "Rock", 1995));
catalogo.add(crearCancion("Mujer divina", "Andrés Cepeda", "Pop/Bolero", 2012));
catalogo.add(crearCancion("En la ciudad de la furia", "Soda Stereo", "Rock", 1988));
catalogo.add(crearCancion("Ella usó mi cabeza como un revólver", "Soda Stereo", "Rock", 1995));
catalogo.add(crearCancion("La flaca", "Jarabe de Palo", "Rock/Pop", 1996));
catalogo.add(crearCancion("Rayando el sol", "Maná", "Rock/Pop", 1990));
catalogo.add(crearCancion("Mil horas", "Los Abuelos de la Nada", "Rock", 1983));
catalogo.add(crearCancion("Flor de un día", "Intoxicados", "Rock", 2005));
catalogo.add(crearCancion("Todo un palo", "Patricio Rey y sus Redonditos de Ricota", "Rock", 1986));
catalogo.add(crearCancion("Pasa el tiempo", "La Beriso", "Rock", 2013));
catalogo.add(crearCancion("Un beso y una flor", "Nino Bravo", "Pop", 1972));
catalogo.add(crearCancion("Me vas a extrañar", "Nicky Jam", "Reggaeton/Romántico", 2015));
